# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='word',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
